version: '3'
services:

  postgresql:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_DB=orderprocessingdb

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2191:2181 
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "batchOrder"